### ISSUE TITLE
Bundle agent with the main package

### ISSUE THREAD

**Issue by algomaster99** [ASSERT-KTH/collector-sahab#149]
Currently, we hardcode the path to the agent [here](https://github.com/ASSERT-KTH/collector-sahab/blob/51724743a0d332835fd74a168f970dc7d1bffa54/main/src/main/java/se/assertkth/cs/preprocess/PomTransformer.java#L28). It would be nice if we can dynamically get the path to the JAR. To do so, we could bundle this while running the assembly plugin.

**Comment by algomaster99** [comment]
Once this ticket is dealt with, we can start releasing JARs on maven central.

**Comment by algomaster99** [comment]
@MartinWit need your help to integrate the release script you wrote so I can also make regular releases of this project. :D

**Comment by MartinWitt** [comment]
I can have a look tomorrow
